### ISSUE TITLE
fix ui for generate with UI button & edit button for image upload on profile page

### ISSUE THREAD

**Issue by aslezar** [aslezar/BlogMinds#110]

**Comment by kshitijtanwar** [comment]
Fixed!!

**Comment by kshitijtanwar** [comment]
https://github.com/aslezar/BlogMinds/assets/115441279/4ec5381a-5014-4062-8cfe-fd17e4b741cb


https://github.com/aslezar/BlogMinds/assets/115441279/d25f7f37-4b76-4a0e-808a-519a0bc24bc4

**Comment by aslezar** [comment]
completed #113
